# This is a basic workflow to help you get started with Actions

name: Release version

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  release:
    types: [published]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: olegtarasov/get-tag@v2
      id: version
      with:
        tagRegex: "v(.*)"  # Optional. Returns specified group text as tag name. Full tag string is returned if regex is not defined.
        tagRegexGroup: 1 # Optional. Default is 1.
    - name: Check version number
      run: echo ${{ steps.version.outputs.tag }}
    - name: Cancel due to wrong version number
      if: steps.version.outputs.tag == null
      run: | 
        echo "Tag name is wrong: ${{ steps.version.outputs.tag }}"
        exit 1
        
  build:
    runs-on: ubuntu-latest
    needs: verify
    steps:
      - name: Build
        run: This shouldn't run if verify is false
