# This is a basic workflow to help you get started with Actions

name: Release version

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  release:
    types: [published]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: olegtarasov/get-tag@v2
      id: version
      with:
        tagRegex: "v(.*)"  # Optional. Returns specified group text as tag name. Full tag string is returned if regex is not defined.
        tagRegexGroup: 1 # Optional. Default is 1.
    - name: Cancel due to wrong version number
      if: steps.version.outputs.tag == null
      run: | 
        echo "Tag name is wrong: ${{ steps.version.outputs.tag }}"
        exit 1
    - name: Save version number
      run: echo ${{ steps.version.outputs.tag }} > version.txt
    - name: Upload version information artifact
      uses: actions/upload-artifact@v1
      with:
        name: version-artifact
        path: version.txt
     
  build:
    runs-on: ubuntu-latest
    needs: verify
    steps:
      - name: Build
        run: echo "This shouldn't run if verify is false"
      - name: Download java artifact
        uses: actions/download-artifact@v2
        with:
          name: version-artifact
      - name: Save version in env
        run: echo "::set-env name=RELEASE_VERSION::$(cat version.txt)"
      - name: Show version
        run: echo ${{ env.RELEASE_VERSION }}
